#include "webpage.h"

const char html_page[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"  <title>F.R.O.G.S. Web App</title>\n"
"\n"
"  <style>\n"
"    :root {\n"
"      --ucf-gold: #d4af37;\n"
"      --ucf-black: #050505;\n"
"      --panel: #121212;\n"
"      --muted: #aaaaaa;\n"
"      --good: #4fe08b;\n"
"      --warn: #ffd34d;\n"
"      --bad: #ff6a6a;\n"
"    }\n"
"\n"
"    * { box-sizing: border-box; }\n"
"\n"
"    body {\n"
"      margin: 0;\n"
"      background-color: var(--ucf-black);\n"
"      color: white;\n"
"      font-family: Arial, sans-serif;\n"
"      padding-bottom: 98px;\n"
"    }\n"
"\n"
"    .app {\n"
"      padding: 25px;\n"
"      max-width: 1400px;\n"
"      margin: 0 auto;\n"
"    }\n"
"\n"
"    h1 {\n"
"      text-align: center;\n"
"      color: var(--ucf-gold);\n"
"      letter-spacing: 2px;\n"
"      margin: 0 0 10px;\n"
"    }\n"
"\n"
"    .subtitle {\n"
"      text-align: center;\n"
"      color: var(--muted);\n"
"      margin: 0 0 25px;\n"
"    }\n"
"\n"
"    .status-card,\n"
"    .sensor-card,\n"
"    .switch-card,\n"
"    .info-card,\n"
"    .override-card {\n"
"      border: 2px solid var(--ucf-gold);\n"
"      border-radius: 18px;\n"
"      padding: 20px;\n"
"      background-color: var(--panel);\n"
"    }\n"
"\n"
"    .status-card {\n"
"      margin-bottom: 25px;\n"
"    }\n"
"\n"
"    .status-card h2,\n"
"    .sensor-card h3,\n"
"    .switch-card h3,\n"
"    .info-card h3,\n"
"    .override-card h3 {\n"
"      color: var(--ucf-gold);\n"
"      margin-top: 0;\n"
"    }\n"
"\n"
"    .sensor-grid {\n"
"      display: grid;\n"
"      grid-template-columns: repeat(4, 1fr);\n"
"      gap: 18px;\n"
"    }\n"
"\n"
"    .sensor-card {\n"
"      text-align: center;\n"
"    }\n"
"\n"
"    .icon {\n"
"      font-size: 32px;\n"
"      margin-bottom: 10px;\n"
"    }\n"
"\n"
"    .value {\n"
"      font-size: 28px;\n"
"      font-weight: bold;\n"
"      margin: 10px 0;\n"
"    }\n"
"\n"
"    .label {\n"
"      color: var(--muted);\n"
"      margin-bottom: 0;\n"
"    }\n"
"\n"
"    .switch-row,\n"
"    .info-grid {\n"
"      display: grid;\n"
"      grid-template-columns: 1fr 1fr;\n"
"      gap: 18px;\n"
"      margin-top: 25px;\n"
"    }\n"
"\n"
"    .switch-card {\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"      align-items: center;\n"
"      gap: 16px;\n"
"    }\n"
"\n"
"    .switch {\n"
"      position: relative;\n"
"      width: 60px;\n"
"      height: 34px;\n"
"      flex: 0 0 auto;\n"
"    }\n"
"\n"
"    .switch input {\n"
"      display: none;\n"
"    }\n"
"\n"
"    .slider {\n"
"      position: absolute;\n"
"      cursor: pointer;\n"
"      inset: 0;\n"
"      background-color: #444;\n"
"      border-radius: 34px;\n"
"      transition: 0.3s;\n"
"    }\n"
"\n"
"    .slider:before {\n"
"      content: \"\";\n"
"      position: absolute;\n"
"      height: 26px;\n"
"      width: 26px;\n"
"      left: 4px;\n"
"      bottom: 4px;\n"
"      background-color: white;\n"
"      border-radius: 50%;\n"
"      transition: 0.3s;\n"
"    }\n"
"\n"
"    input:checked + .slider {\n"
"      background-color: var(--ucf-gold);\n"
"    }\n"
"\n"
"    input:checked + .slider:before {\n"
"      transform: translateX(26px);\n"
"    }\n"
"\n"
"    .refresh-row {\n"
"      margin-top: 25px;\n"
"      text-align: center;\n"
"    }\n"
"\n"
"    .refresh-btn {\n"
"      background-color: var(--ucf-gold);\n"
"      color: black;\n"
"      border: none;\n"
"      border-radius: 14px;\n"
"      padding: 14px 28px;\n"
"      font-size: 18px;\n"
"      font-weight: bold;\n"
"      cursor: pointer;\n"
"    }\n"
"\n"
"    .refresh-btn:active {\n"
"      transform: scale(0.98);\n"
"    }\n"
"\n"
"    .page { display: none; }\n"
"    .page.active { display: block; }\n"
"\n"
"    .section-heading {\n"
"      color: var(--ucf-gold);\n"
"      margin: 0 0 8px;\n"
"    }\n"
"\n"
"    .section-note {\n"
"      color: var(--muted);\n"
"      margin: 0 0 22px;\n"
"    }\n"
"\n"
"    .state-good { color: var(--good); font-weight: bold; }\n"
"    .state-warn { color: var(--warn); font-weight: bold; }\n"
"    .state-bad { color: var(--bad); font-weight: bold; }\n"
"\n"
"    .setting-row {\n"
"      display: grid;\n"
"      grid-template-columns: 1.2fr 1fr;\n"
"      gap: 12px;\n"
"      align-items: center;\n"
"      border-top: 1px solid #343434;\n"
"      padding: 14px 0;\n"
"    }\n"
"\n"
"    .setting-row:first-of-type { border-top: 0; }\n"
"\n"
"    .setting-row input {\n"
"      width: 100%;\n"
"      padding: 10px 12px;\n"
"      background: #050505;\n"
"      color: white;\n"
"      border: 1px solid var(--ucf-gold);\n"
"      border-radius: 10px;\n"
"      font-size: 16px;\n"
"    }\n"
"\n"
"    .small-note {\n"
"      color: var(--muted);\n"
"      font-size: 14px;\n"
"      line-height: 1.45;\n"
"    }\n"
"\n"
"    .bottom-tabs {\n"
"      position: fixed;\n"
"      z-index: 20;\n"
"      left: 0;\n"
"      right: 0;\n"
"      bottom: 0;\n"
"      background: #0d0d0d;\n"
"      border-top: 2px solid var(--ucf-gold);\n"
"      display: flex;\n"
"      justify-content: center;\n"
"      gap: 4px;\n"
"      padding: 10px max(10px, env(safe-area-inset-right)) calc(10px + env(safe-area-inset-bottom)) max(10px, env(safe-area-inset-left));\n"
"      overflow-x: auto;\n"
"    }\n"
"\n"
"    .tab-btn {\n"
"      background: transparent;\n"
"      color: #d9d9d9;\n"
"      border: 1px solid transparent;\n"
"      border-radius: 12px;\n"
"      padding: 11px 15px;\n"
"      font-weight: bold;\n"
"      cursor: pointer;\n"
"      white-space: nowrap;\n"
"      min-width: 86px;\n"
"    }\n"
"\n"
"    .tab-btn.active {\n"
"      background: var(--ucf-gold);\n"
"      color: black;\n"
"      border-color: var(--ucf-gold);\n"
"    }\n"
"\n"
"    .override-actions {\n"
"      display: flex;\n"
"      gap: 12px;\n"
"      flex-wrap: wrap;\n"
"      margin-top: 14px;\n"
"    }\n"
"\n"
"    .override-btn {\n"
"      border: 1px solid var(--ucf-gold);\n"
"      background: #050505;\n"
"      color: white;\n"
"      border-radius: 12px;\n"
"      padding: 11px 15px;\n"
"      font-size: 15px;\n"
"      font-weight: bold;\n"
"      cursor: pointer;\n"
"    }\n"
"\n"
"    .override-btn.active {\n"
"      background: var(--ucf-gold);\n"
"      color: black;\n"
"    }\n"
"\n"
"    .override-btn.stop {\n"
"      border-color: #ff6a6a;\n"
"      color: #ff8d8d;\n"
"    }\n"
"\n"
"    .override-btn.stop.active {\n"
"      background: #ff6a6a;\n"
"      color: black;\n"
"    }\n"
"\n"
"    .admin-warning {\n"
"      border: 1px solid #ffbf47;\n"
"      background: #2b210c;\n"
"      border-radius: 12px;\n"
"      padding: 13px;\n"
"      margin-top: 18px;\n"
"      line-height: 1.45;\n"
"    }\n"
"\n"
"    @media (max-width: 1050px) {\n"
"      .sensor-grid { grid-template-columns: repeat(2, 1fr); }\n"
"    }\n"
"\n"
"    @media (max-width: 650px) {\n"
"      .app { padding: 18px; }\n"
"      .sensor-grid,\n"
"      .switch-row,\n"
"      .info-grid { grid-template-columns: 1fr; }\n"
"      .status-card,\n"
"      .sensor-card,\n"
"      .switch-card,\n"
"      .info-card,\n"
"      .override-card { padding: 17px; }\n"
"      h1 { font-size: 24px; }\n"
"      .tab-btn { min-width: 72px; padding: 10px 11px; font-size: 12px; }\n"
"    }\n"
"  </style>\n"
"</head>\n"
"\n"
"<body>\n"
"  <div class=\"app\">\n"
"    <h1>F.R.O.G.S. Water System</h1>\n"
"    <p class=\"subtitle\">Filtration Resource for Off-Grid Systems · Monitor on Home · Configure in Admin</p>\n"
"\n"
"    <section id=\"homePage\" class=\"page active\">\n"
"      <div class=\"status-card\">\n"
"        <h2>System Status</h2>\n"
"        <p id=\"connectionStatus\">❌ Device Disconnected</p>\n"
"        <p id=\"wifiStatus\">⚠️ Waiting for ESP32 connection...</p>\n"
"        <p id=\"systemBlock\">System state: <span class=\"state-warn\">WAITING FOR DATA</span></p>\n"
"      </div>\n"
"\n"
"      <div class=\"sensor-grid\">\n"
"        <div class=\"sensor-card\">\n"
"          <div class=\"icon\">💧</div>\n"
"          <h3>TDS</h3>\n"
"          <p class=\"value\" id=\"tdsValue\">-- ppm</p>\n"
"          <p class=\"label\">Water Purity</p>\n"
"        </div>\n"
"\n"
"        <div class=\"sensor-card\">\n"
"          <div class=\"icon\">🌡️</div>\n"
"          <h3>Temperature</h3>\n"
"          <p class=\"value\" id=\"tempValue\">-- °F</p>\n"
"          <p class=\"label\">Water Temperature</p>\n"
"        </div>\n"
"\n"
"        <div class=\"sensor-card\">\n"
"          <div class=\"icon\">🌊</div>\n"
"          <h3>Flow 1</h3>\n"
"          <p class=\"value\" id=\"flowValue\">-- GPM</p>\n"
"          <p class=\"label\">Input Water Flow</p>\n"
"        </div>\n"
"\n"
"        <div class=\"sensor-card\">\n"
"          <div class=\"icon\">🚰</div>\n"
"          <h3>Flow 2</h3>\n"
"          <p class=\"value\" id=\"homeFlow2Value\">-- GPM</p>\n"
"          <p class=\"label\">Output Water Flow</p>\n"
"        </div>\n"
"\n"
"        <div class=\"sensor-card\">\n"
"          <div class=\"icon\">📊</div>\n"
"          <h3>F1 : F2</h3>\n"
"          <p class=\"value\" id=\"homeRatioValue\">-- : --</p>\n"
"          <p class=\"label\">Direct Flow Values</p>\n"
"        </div>\n"
"\n"
"        <div class=\"sensor-card\">\n"
"          <div class=\"icon\">🔋</div>\n"
"          <h3>Battery</h3>\n"
"          <p class=\"value\" id=\"batteryValue\">-- V</p>\n"
"          <p class=\"label\">Battery Voltage</p>\n"
"        </div>\n"
"\n"
"        <div class=\"sensor-card\">\n"
"          <div class=\"icon\">🪣</div>\n"
"          <h3>Tank Status</h3>\n"
"          <p class=\"value\" id=\"tankStatusValue\">--</p>\n"
"          <p class=\"label\" id=\"tankStatusDetail\">Float Switch: --</p>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"switch-row\">\n"
"        <div class=\"switch-card\">\n"
"          <div>\n"
"            <h3>Pump 1 Enable</h3>\n"
"            <p class=\"small-note\">Requests low-pressure pump operation. Firmware safety rules remain active.</p>\n"
"          </div>\n"
"          <label class=\"switch\">\n"
"            <input type=\"checkbox\" id=\"pump1Switch\" onchange=\"setPump1(this.checked)\">\n"
"            <span class=\"slider\"></span>\n"
"          </label>\n"
"        </div>\n"
"\n"
"        <div class=\"switch-card\">\n"
"          <div>\n"
"            <h3>Pump 2 Enable</h3>\n"
"            <p class=\"small-note\">Requests high-pressure pump operation. Firmware safety rules remain active.</p>\n"
"          </div>\n"
"          <label class=\"switch\">\n"
"            <input type=\"checkbox\" id=\"pump2Switch\" onchange=\"setPump2(this.checked)\">\n"
"            <span class=\"slider\"></span>\n"
"          </label>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"refresh-row\">\n"
"        <button class=\"refresh-btn\" onclick=\"getSensorData()\">Refresh Data</button>\n"
"      </div>\n"
"    </section>\n"
"\n"
"    <section id=\"adminPage\" class=\"page\">\n"
"      <h2 class=\"section-heading\">Admin Settings</h2>\n"
"      <p class=\"section-note\">Maintenance and protection settings. Readouts update from the ESP32 when the matching values are included in <code>/data</code>.</p>\n"
"\n"
"      <div class=\"status-card\">\n"
"        <h2>System Admin Mode</h2>\n"
"        <div class=\"switch-card\" style=\"margin-top:16px;\">\n"
"          <div>\n"
"            <h3 style=\"margin-bottom:6px;\">Stop Pump Operation</h3>\n"
"            <p class=\"small-note\">When enabled, both pumps are forced off. The OLED, sensors, Wi-Fi, and webpage remain active so the system can still be monitored and Admin Mode can be turned off.</p>\n"
"            <p id=\"adminModeStatus\" class=\"state-good\">Admin Mode: OFF — normal pump control</p>\n"
"          </div>\n"
"          <label class=\"switch\">\n"
"            <input type=\"checkbox\" id=\"adminModeSwitch\" onchange=\"setAdminMode(this.checked)\">\n"
"            <span class=\"slider\"></span>\n"
"          </label>\n"
"        </div>\n"
"        <p id=\"adminModeNotice\" class=\"small-note\" style=\"text-align:center; margin:14px 0 0;\"></p>\n"
"      </div>\n"
"\n"
"      <div class=\"status-card\">\n"
"        <h2>Autonomous Mode</h2>\n"
"        <div class=\"switch-card\" style=\"margin-top:16px;\">\n"
"          <div>\n"
"            <h3 style=\"margin-bottom:6px;\">Enable Autonomous Mode</h3>\n"
"            <p class=\"small-note\">One-time preset: turns on LP Enable, HP Enable, Float Switch Check, and Voltage Protection Check, and clears the LP override. Those settings stay independently editable afterward — this switch does not stay \"locked on\".</p>\n"
"            <p id=\"autonomousModeStatus\" class=\"state-warn\">Autonomous Mode: OFF</p>\n"
"          </div>\n"
"          <label class=\"switch\">\n"
"            <input type=\"checkbox\" id=\"autonomousModeSwitch\" onchange=\"setAutonomousMode(this.checked)\">\n"
"            <span class=\"slider\"></span>\n"
"          </label>\n"
"        </div>\n"
"        <p id=\"autonomousModeNotice\" class=\"small-note\" style=\"text-align:center; margin:14px 0 0;\"></p>\n"
"      </div>\n"
"\n"
"      <div class=\"info-grid\">\n"
"        <div class=\"info-card\">\n"
"          <h3>Current Protection Status</h3>\n"
"          <div class=\"setting-row\"><span>Battery Voltage Now</span><strong id=\"adminBatteryReadout\">-- V</strong></div>\n"
"          <div class=\"setting-row\"><span>Low-Voltage Disconnect (LVD)</span><strong id=\"lvdReadout\">-- V</strong></div>\n"
"          <div class=\"setting-row\"><span>Minimum Voltage Restart (MVR)</span><strong id=\"mvrReadout\">-- V</strong></div>\n"
"          <div class=\"setting-row\"><span>Minimum Flow</span><strong id=\"minFlowReadout\">-- GPM</strong></div>\n"
"        </div>\n"
"\n"
"        <div class=\"info-card\">\n"
"          <h3>Voltage Protection Control</h3>\n"
"          <p class=\"small-note\">LVD is the shutdown voltage. MVR is the voltage required before the system is allowed to restart.</p>\n"
"\n"
"          <div class=\"setting-row\">\n"
"            <label for=\"lvdSlider\">Shutdown Voltage (LVD)</label>\n"
"            <div>\n"
"              <input id=\"lvdSlider\" type=\"range\" min=\"10.5\" max=\"14.6\" step=\"0.1\" value=\"12.0\" oninput=\"syncVoltageInputs('lvd')\">\n"
"              <input id=\"lvdInput\" type=\"number\" min=\"10.5\" max=\"14.6\" step=\"0.1\" value=\"12.0\" oninput=\"syncVoltageInputs('lvd', true)\">\n"
"            </div>\n"
"          </div>\n"
"\n"
"          <div class=\"setting-row\">\n"
"            <label for=\"mvrSlider\">Restart Voltage (MVR)</label>\n"
"            <div>\n"
"              <input id=\"mvrSlider\" type=\"range\" min=\"10.5\" max=\"14.6\" step=\"0.1\" value=\"12.8\" oninput=\"syncVoltageInputs('mvr')\">\n"
"              <input id=\"mvrInput\" type=\"number\" min=\"10.5\" max=\"14.6\" step=\"0.1\" value=\"12.8\" oninput=\"syncVoltageInputs('mvr', true)\">\n"
"            </div>\n"
"          </div>\n"
"\n"
"          <div class=\"refresh-row\"><button class=\"refresh-btn\" onclick=\"saveProtectionSettings()\">Apply Voltage Settings</button></div>\n"
"          <p id=\"adminNotice\" class=\"small-note\" style=\"text-align:center;\"></p>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"status-card\" style=\"margin-top:25px;\">\n"
"        <h2>Protection Rule</h2>\n"
"        <p id=\"voltageRuleText\" class=\"state-warn\">The system will shut down at -- V and may restart at -- V.</p>\n"
"        <p class=\"small-note\">The webpage is ready for the admin save routes, but read/display works independently through <code>/data</code>.</p>\n"
"      </div>\n"
"\n"
"      <div class=\"info-grid\">\n"
"        <div class=\"override-card\">\n"
"          <h3>Low-Pressure Pump Override</h3>\n"
"          <p id=\"lpOverrideState\" class=\"state-warn\">Override: OFF</p>\n"
"          <p class=\"small-note\">Use only for supervised maintenance and troubleshooting.</p>\n"
"          <div class=\"override-actions\">\n"
"            <button id=\"lpOverrideOnBtn\" class=\"override-btn\" onclick=\"setPumpOverride('lp', true)\">Enable Override</button>\n"
"            <button id=\"lpOverrideOffBtn\" class=\"override-btn stop active\" onclick=\"setPumpOverride('lp', false)\">Disable Override</button>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"admin-warning\">\n"
"        <strong>Important:</strong> only the low-pressure pump has a temporary maintenance override. The high-pressure pump remains protected from Admin override commands.\n"
"      </div>\n"
"      <p id=\"overrideNotice\" class=\"small-note\" style=\"text-align:center; margin-top:14px;\"></p>\n"
"\n"
"      <div class=\"status-card\" style=\"margin-top:25px;\">\n"
"        <h2 style=\"margin-bottom:8px;\">Safety Condition Checks</h2>\n"
"        <p class=\"small-note\">These match the OLED Admin Edit checks already in firmware, but are written out more clearly for the web app.</p>\n"
"\n"
"        <div class=\"info-grid\" style=\"margin-top:18px;\">\n"
"          <div class=\"switch-card\">\n"
"            <div>\n"
"              <h3>Float Switch Check</h3>\n"
"              <p id=\"floatCheckStatus\" class=\"small-note\">Tank float check: ENABLED</p>\n"
"            </div>\n"
"            <label class=\"switch\">\n"
"              <input type=\"checkbox\" id=\"floatCheckSwitch\" checked onchange=\"setConditionCheck('float', this.checked)\">\n"
"              <span class=\"slider\"></span>\n"
"            </label>\n"
"          </div>\n"
"\n"
"          <div class=\"switch-card\">\n"
"            <div>\n"
"              <h3>Voltage Protection Check</h3>\n"
"              <p id=\"lvdCheckStatus\" class=\"small-note\">Low-voltage check: ENABLED</p>\n"
"            </div>\n"
"            <label class=\"switch\">\n"
"              <input type=\"checkbox\" id=\"lvdCheckSwitch\" checked onchange=\"setConditionCheck('lvd', this.checked)\">\n"
"              <span class=\"slider\"></span>\n"
"            </label>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"admin-warning\" style=\"margin-top:18px;\">\n"
"          <strong>Safety note:</strong> these switches map directly to <code>g_float_check</code> and <code>g_lvd_check</code>. They are the same checks shown on the OLED Admin screen, just written out with clearer names.\n"
"        </div>\n"
"\n"
"        <p id=\"conditionNotice\" class=\"small-note\" style=\"text-align:center; margin:18px 0 0;\"></p>\n"
"      </div>\n"
"\n"
"      <div class=\"status-card\" style=\"margin-top:25px;\">\n"
"        <h2>Reset Defaults</h2>\n"
"        <p class=\"small-note\">Restores the Admin protection settings back to the firmware default values. This should match the OLED RESET DEFAULTS option.</p>\n"
"        <div class=\"refresh-row\">\n"
"          <button class=\"refresh-btn\" onclick=\"resetDefaults()\">Reset Admin Defaults</button>\n"
"        </div>\n"
"        <p id=\"resetNotice\" class=\"small-note\" style=\"text-align:center; margin-top:14px;\"></p>\n"
"      </div>\n"
"    </section>\n"
"  </div>\n"
"\n"
"  <nav class=\"bottom-tabs\" aria-label=\"FROGS app pages\">\n"
"    <button class=\"tab-btn active\" data-page=\"homePage\">HOME</button>\n"
"    <button class=\"tab-btn\" data-page=\"adminPage\">ADMIN</button>\n"
"  </nav>\n"
"\n"
"  <script>\n"
"    const demoData = {\n"
"      tds: 184,\n"
"      temperature: 74.3,\n"
"      flowRate: 1.25,\n"
"      flow1: 1.42,\n"
"      flow2: 1.18,\n"
"      battery: 12.6,\n"
"      pump1Enabled: false,\n"
"      pump2Enabled: false,\n"
"      tank: \"LOW\",\n"
"      blocked: \"NONE\",\n"
"      lvd: 12.0,\n"
"      mvr: 12.8,\n"
"      minFlow: 0.40,\n"
"      lpOverride: false,\n"
"      autonomousMode: false,\n"
"      conditionChecks: {\n"
"        float: true,\n"
"        lvd: true\n"
"      },\n"
"      floatUp: false\n"
"    };\n"
"\n"
"    let lastData = {};\n"
"    let demoMode = false;\n"
"    let webAdminMode = false;\n"
"\n"
"    function setText(id, value) {\n"
"      const el = document.getElementById(id);\n"
"      if (el) el.innerText = value;\n"
"    }\n"
"\n"
"    function setChecked(id, checked) {\n"
"      const el = document.getElementById(id);\n"
"      if (el) el.checked = Boolean(checked);\n"
"    }\n"
"\n"
"    function setClass(id, className) {\n"
"      const el = document.getElementById(id);\n"
"      if (el) el.className = className;\n"
"    }\n"
"\n"
"    function boolText(value) {\n"
"      return value ? \"ON\" : \"OFF\";\n"
"    }\n"
"\n"
"    function firstDefined(data, names, fallback) {\n"
"      for (const name of names) {\n"
"        if (data[name] !== undefined && data[name] !== null) return data[name];\n"
"      }\n"
"      return fallback;\n"
"    }\n"
"\n"
"    function toBool(value, fallback = false) {\n"
"      if (value === undefined || value === null) return fallback;\n"
"      if (typeof value === \"boolean\") return value;\n"
"      if (typeof value === \"number\") return value !== 0;\n"
"      if (typeof value === \"string\") {\n"
"        const v = value.trim().toLowerCase();\n"
"        if ([\"true\", \"1\", \"on\", \"enabled\", \"yes\", \"day\", \"full\", \"up\"].includes(v)) return true;\n"
"        if ([\"false\", \"0\", \"off\", \"disabled\", \"no\", \"night\", \"low\", \"down\"].includes(v)) return false;\n"
"      }\n"
"      return fallback;\n"
"    }\n"
"\n"
"    function valueExists(value) {\n"
"      return value !== undefined && value !== null && value !== \"--\" && value !== \"UNKNOWN\";\n"
"    }\n"
"\n"
"    function formatValue(value, digits = 1) {\n"
"      const n = Number(value);\n"
"      return Number.isFinite(n) ? n.toFixed(digits) : \"--\";\n"
"    }\n"
"\n"
"    function buildConditionChecks(data) {\n"
"      const nested = firstDefined(data, [\"conditionChecks\", \"checks\"], null);\n"
"      if (nested && typeof nested === \"object\") {\n"
"        return {\n"
"          float: toBool(firstDefined(nested, [\"float\", \"floatCheck\", \"float_check\"], true), true),\n"
"          lvd: toBool(firstDefined(nested, [\"lvd\", \"lvdCheck\", \"lvd_check\"], true), true)\n"
"        };\n"
"      }\n"
"\n"
"      const oldNested = firstDefined(data, [\"sensorStates\", \"sensor_states\"], null);\n"
"      return {\n"
"        float: toBool(firstDefined(data, [\"floatCheck\", \"float_check\"], oldNested ? oldNested.float : true), true),\n"
"        lvd: toBool(firstDefined(data, [\"lvdCheck\", \"lvd_check\"], oldNested ? oldNested.battery : true), true)\n"
"      };\n"
"    }\n"
"\n"
"    function updatePage(data) {\n"
"      const tds = firstDefined(data, [\"tds\", \"tdsPpm\"], \"--\");\n"
"      const temperature = firstDefined(data, [\"temperature\", \"temp\", \"tempF\"], \"--\");\n"
"      const flow1 = firstDefined(data, [\"flow1\", \"inputFlow\", \"flowRate\", \"flow\"], \"--\");\n"
"      const flow2 = firstDefined(data, [\"flow2\", \"outputFlow\"], \"--\");\n"
"      const battery = firstDefined(data, [\"battery\", \"batteryVoltage\", \"battery_voltage\"], \"--\");\n"
"\n"
"      const pump1 = toBool(firstDefined(data, [\"pump1Enabled\", \"lpPumpEnabled\", \"lpEnabled\", \"lpPumpEnable\", \"lp_enable\"], false));\n"
"      const pump2 = toBool(firstDefined(data, [\"pump2Enabled\", \"hpPumpEnabled\", \"hpEnabled\", \"hpPumpEnable\", \"hp_enable\"], false));\n"
"\n"
"      setText(\"tdsValue\", formatValue(tds, 1) + \" ppm\");\n"
"      setText(\"tempValue\", formatValue(temperature, 1) + \" °F\");\n"
"      setText(\"flowValue\", formatValue(flow1, 2) + \" GPM\");\n"
"      setText(\"homeFlow2Value\", formatValue(flow2, 2) + \" GPM\");\n"
"      setText(\"batteryValue\", formatValue(battery, 2) + \" V\");\n"
"\n"
"      const n1 = Number(flow1);\n"
"      const n2 = Number(flow2);\n"
"      const flowPair = (Number.isFinite(n1) && Number.isFinite(n2))\n"
"        ? n1.toFixed(2) + \" : \" + n2.toFixed(2)\n"
"        : formatValue(flow1, 2) + \" : \" + formatValue(flow2, 2);\n"
"      setText(\"homeRatioValue\", flowPair);\n"
"\n"
"      setChecked(\"pump1Switch\", pump1);\n"
"      setChecked(\"pump2Switch\", pump2);\n"
"\n"
"      const floatRaw = firstDefined(data, [\"floatUp\", \"floatSwitchUp\", \"floatState\", \"tankFloat\", \"tankFull\", \"tank_full\"], undefined);\n"
"      const tankRaw = firstDefined(data, [\"tank\", \"tankStatus\", \"tank_status\"], undefined);\n"
"\n"
"      if (valueExists(floatRaw)) {\n"
"        const floatIsUp = toBool(floatRaw, false);\n"
"        setText(\"tankStatusValue\", floatIsUp ? \"LOW\" : \"FULL\");\n"
"        setText(\"tankStatusDetail\", \"Float Switch: \" + (floatIsUp ? \"UP\" : \"DOWN\"));\n"
"        setClass(\"tankStatusValue\", \"value \" + (floatIsUp ? \"state-good\" : \"state-warn\"));\n"
"      } else if (valueExists(tankRaw)) {\n"
"        const tankText = String(tankRaw).toUpperCase();\n"
"        setText(\"tankStatusValue\", tankText);\n"
"        setText(\"tankStatusDetail\", \"Float Switch: state not provided\");\n"
"        setClass(\"tankStatusValue\", \"value \" + ([\"OK\", \"FULL\"].includes(tankText) ? \"state-good\" : \"state-warn\"));\n"
"      } else {\n"
"        setText(\"tankStatusValue\", \"UNKNOWN\");\n"
"        setText(\"tankStatusDetail\", \"Float Switch: no data\");\n"
"        setClass(\"tankStatusValue\", \"value state-warn\");\n"
"      }\n"
"\n"
"      const blocked = firstDefined(data, [\"blocked\", \"blockReason\", \"block_reason\"], \"NONE\");\n"
"      const blockedEl = document.getElementById(\"systemBlock\");\n"
"      const clearState = blocked === \"NONE\" || blocked === \"OK\" || blocked === false;\n"
"      blockedEl.innerHTML = \"System state: <span class='\" + (clearState ? \"state-good\" : \"state-warn\") + \"'>\" + (clearState ? \"SYSTEM OK\" : \"BLOCKED: \" + blocked) + \"</span>\";\n"
"\n"
"      const lvd = firstDefined(data, [\"lvd\", \"lowVoltageDisconnect\"], undefined);\n"
"      const mvr = firstDefined(data, [\"mvr\", \"minimumVoltageRestart\"], undefined);\n"
"      const minFlow = firstDefined(data, [\"minFlow\", \"minimumFlow\", \"min_flow\"], undefined);\n"
"      const lpOverride = toBool(firstDefined(data, [\"lpOverride\", \"lp_override\", \"lpPumpOverride\"], false), false);\n"
"      const autonomousMode = toBool(firstDefined(data, [\"autonomousMode\", \"autonomous_mode\"], false), false);\n"
"\n"
"      setText(\"adminBatteryReadout\", formatValue(battery, 2) + \" V\");\n"
"      setText(\"lvdReadout\", valueExists(lvd) ? formatValue(lvd, 2) + \" V\" : \"-- V\");\n"
"      setText(\"mvrReadout\", valueExists(mvr) ? formatValue(mvr, 2) + \" V\" : \"-- V\");\n"
"      setText(\"minFlowReadout\", valueExists(minFlow) ? formatValue(minFlow, 2) + \" GPM\" : \"-- GPM\");\n"
"\n"
"      updateOverrideDisplay(\"lp\", lpOverride);\n"
"      updateAutonomousModeDisplay(autonomousMode);\n"
"      updateConditionDisplays(buildConditionChecks(data));\n"
"\n"
"      const displayLvd = valueExists(lvd) ? Number(lvd).toFixed(1) : \"--\";\n"
"      const displayMvr = valueExists(mvr) ? Number(mvr).toFixed(1) : \"--\";\n"
"      setText(\"voltageRuleText\", \"The system will shut down at \" + displayLvd + \" V and may restart at \" + displayMvr + \" V.\");\n"
"\n"
"      if (valueExists(lvd) &&\n"
"          document.activeElement !== document.getElementById(\"lvdInput\") &&\n"
"          document.activeElement !== document.getElementById(\"lvdSlider\")) {\n"
"        document.getElementById(\"lvdInput\").value = Number(lvd).toFixed(1);\n"
"        document.getElementById(\"lvdSlider\").value = Number(lvd).toFixed(1);\n"
"      }\n"
"\n"
"      if (valueExists(mvr) &&\n"
"          document.activeElement !== document.getElementById(\"mvrInput\") &&\n"
"          document.activeElement !== document.getElementById(\"mvrSlider\")) {\n"
"        document.getElementById(\"mvrInput\").value = Number(mvr).toFixed(1);\n"
"        document.getElementById(\"mvrSlider\").value = Number(mvr).toFixed(1);\n"
"      }\n"
"    }\n"
"\n"
"    function updateAdminModeDisplay(enabled) {\n"
"      webAdminMode = Boolean(enabled);\n"
"      setChecked(\"adminModeSwitch\", webAdminMode);\n"
"\n"
"      const statusEl = document.getElementById(\"adminModeStatus\");\n"
"      if (statusEl) {\n"
"        statusEl.textContent = webAdminMode\n"
"          ? \"Admin Mode: ON — both pumps are forced off\"\n"
"          : \"Admin Mode: OFF — normal pump control\";\n"
"        statusEl.className = webAdminMode ? \"state-bad\" : \"state-good\";\n"
"      }\n"
"\n"
"      const pump1Switch = document.getElementById(\"pump1Switch\");\n"
"      const pump2Switch = document.getElementById(\"pump2Switch\");\n"
"      if (pump1Switch) pump1Switch.disabled = webAdminMode;\n"
"      if (pump2Switch) pump2Switch.disabled = webAdminMode;\n"
"    }\n"
"\n"
"    async function getAdminMode() {\n"
"      if (demoMode) {\n"
"        updateAdminModeDisplay(webAdminMode);\n"
"        return;\n"
"      }\n"
"\n"
"      try {\n"
"        const response = await fetch(\"/admin/mode\", { cache: \"no-store\" });\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        const data = await response.json();\n"
"        updateAdminModeDisplay(toBool(data.enabled, false));\n"
"      } catch (error) {\n"
"        setText(\"adminModeNotice\", \"Unable to read Admin Mode from the ESP32.\");\n"
"      }\n"
"    }\n"
"\n"
"    async function setAdminMode(enabled) {\n"
"      const confirmationText = enabled\n"
"        ? \"Enable System Admin Mode? Both pumps will be forced off until Admin Mode is disabled.\"\n"
"        : \"Disable System Admin Mode and return the pumps to normal automatic control?\";\n"
"\n"
"      if (!window.confirm(confirmationText)) {\n"
"        setChecked(\"adminModeSwitch\", !enabled);\n"
"        return;\n"
"      }\n"
"\n"
"      if (demoMode) {\n"
"        updateAdminModeDisplay(enabled);\n"
"        setText(\"adminModeNotice\", enabled\n"
"          ? \"Demo mode: both pumps are shown as stopped.\"\n"
"          : \"Demo mode: normal pump control restored.\");\n"
"        return;\n"
"      }\n"
"\n"
"      try {\n"
"        const response = await fetch(\"/admin/mode?enabled=\" + (enabled ? \"1\" : \"0\"), {\n"
"          cache: \"no-store\"\n"
"        });\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        const data = await response.json();\n"
"        updateAdminModeDisplay(toBool(data.enabled, enabled));\n"
"        setText(\"adminModeNotice\", enabled\n"
"          ? \"Admin Mode enabled. Both pumps are forced off.\"\n"
"          : \"Admin Mode disabled. Normal pump control restored.\");\n"
"        getSensorData();\n"
"      } catch (error) {\n"
"        setChecked(\"adminModeSwitch\", !enabled);\n"
"        setText(\"adminModeNotice\", \"Firmware did not accept the Admin Mode command.\");\n"
"      }\n"
"    }\n"
"\n"
"    async function getSensorData() {\n"
"      try {\n"
"        const response = await fetch(\"/data\", { cache: \"no-store\" });\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        const data = await response.json();\n"
"\n"
"        demoMode = false;\n"
"        lastData = { ...data };\n"
"        updatePage(lastData);\n"
"\n"
"        setText(\"connectionStatus\", \"✅ Device Connected\");\n"
"        setText(\"wifiStatus\", \"ESP32 data received successfully.\");\n"
"        getAdminMode();\n"
"      } catch (error) {\n"
"        demoMode = true;\n"
"        lastData = { ...demoData };\n"
"        updatePage(lastData);\n"
"\n"
"        setText(\"connectionStatus\", \"🟡 Demo Mode\");\n"
"        setText(\"wifiStatus\", \"Open this webpage through the ESP32 to use live /data values.\");\n"
"        updateAdminModeDisplay(webAdminMode);\n"
"      }\n"
"    }\n"
"\n"
"    async function setPump1(enabled) {\n"
"      if (demoMode) {\n"
"        lastData.pump1Enabled = enabled;\n"
"        updatePage(lastData);\n"
"        return;\n"
"      }\n"
"      try {\n"
"        await fetch(enabled ? \"/lp/enable\" : \"/lp/disable\");\n"
"      } finally {\n"
"        getSensorData();\n"
"      }\n"
"    }\n"
"\n"
"    async function setPump2(enabled) {\n"
"      if (demoMode) {\n"
"        lastData.pump2Enabled = enabled;\n"
"        updatePage(lastData);\n"
"        return;\n"
"      }\n"
"      try {\n"
"        await fetch(enabled ? \"/hp/enable\" : \"/hp/disable\");\n"
"      } finally {\n"
"        getSensorData();\n"
"      }\n"
"    }\n"
"\n"
"    const conditionConfig = {\n"
"      float: {\n"
"        switchId: \"floatCheckSwitch\",\n"
"        statusId: \"floatCheckStatus\",\n"
"        name: \"Float Switch Check\",\n"
"        statusPrefix: \"Tank float check\"\n"
"      },\n"
"      lvd: {\n"
"        switchId: \"lvdCheckSwitch\",\n"
"        statusId: \"lvdCheckStatus\",\n"
"        name: \"Voltage Protection Check\",\n"
"        statusPrefix: \"Low-voltage check\"\n"
"      }\n"
"    };\n"
"\n"
"    function updateConditionDisplays(checks) {\n"
"      Object.entries(conditionConfig).forEach(([key, config]) => {\n"
"        const enabled = toBool(checks[key], true);\n"
"        setChecked(config.switchId, enabled);\n"
"        const statusEl = document.getElementById(config.statusId);\n"
"        if (statusEl) {\n"
"          statusEl.textContent = config.statusPrefix + \": \" + (enabled ? \"ENABLED\" : \"DISABLED\");\n"
"          statusEl.className = enabled ? \"state-good\" : \"state-warn\";\n"
"        }\n"
"      });\n"
"    }\n"
"\n"
"    async function setConditionCheck(check, enabled) {\n"
"      const config = conditionConfig[check];\n"
"      if (!config) return;\n"
"\n"
"      const confirmationText = enabled\n"
"        ? \"Enable \" + config.name + \"?\"\n"
"        : \"Disable \" + config.name + \"? This should only be done for supervised maintenance or troubleshooting.\";\n"
"\n"
"      if (!window.confirm(confirmationText)) {\n"
"        setChecked(config.switchId, !enabled);\n"
"        return;\n"
"      }\n"
"\n"
"      if (demoMode) {\n"
"        if (!lastData.conditionChecks) lastData.conditionChecks = buildConditionChecks(lastData);\n"
"        lastData.conditionChecks[check] = enabled;\n"
"        updatePage(lastData);\n"
"        setText(\"conditionNotice\", config.name + \" is now \" + (enabled ? \"enabled.\" : \"disabled.\") + \" (demo mode)\");\n"
"        return;\n"
"      }\n"
"\n"
"      try {\n"
"        const response = await fetch(\"/admin/check\", {\n"
"          method: \"POST\",\n"
"          headers: { \"Content-Type\": \"application/json\" },\n"
"          body: JSON.stringify({ check, enabled })\n"
"        });\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        setText(\"conditionNotice\", config.name + \" is now \" + (enabled ? \"enabled.\" : \"disabled.\"));\n"
"        getSensorData();\n"
"      } catch (error) {\n"
"        setChecked(config.switchId, !enabled);\n"
"        setText(\"conditionNotice\", \"Firmware still needs the /admin/check route before this switch can control \" + config.name + \".\");\n"
"      }\n"
"    }\n"
"\n"
"    function updateOverrideDisplay(pump, enabled) {\n"
"      const stateEl = document.getElementById(pump + \"OverrideState\");\n"
"      const onBtn = document.getElementById(pump + \"OverrideOnBtn\");\n"
"      const offBtn = document.getElementById(pump + \"OverrideOffBtn\");\n"
"      if (!stateEl || !onBtn || !offBtn) return;\n"
"\n"
"      stateEl.textContent = \"Override: \" + (enabled ? \"ON\" : \"OFF\");\n"
"      stateEl.className = enabled ? \"state-bad\" : \"state-warn\";\n"
"      onBtn.classList.toggle(\"active\", enabled);\n"
"      offBtn.classList.toggle(\"active\", !enabled);\n"
"    }\n"
"\n"
"    async function setPumpOverride(pump, enabled) {\n"
"      if (pump !== \"lp\") {\n"
"        setText(\"overrideNotice\", \"High-pressure pump override is disabled for protection.\");\n"
"        return;\n"
"      }\n"
"\n"
"      const confirmationText = enabled\n"
"        ? \"Enable the low-pressure pump maintenance override? This should only be used while someone is actively supervising the system.\"\n"
"        : \"Disable the low-pressure pump override and return to normal safety control?\";\n"
"\n"
"      if (!window.confirm(confirmationText)) return;\n"
"\n"
"      if (demoMode) {\n"
"        lastData.lpOverride = enabled;\n"
"        updatePage(lastData);\n"
"        setText(\"overrideNotice\", \"Low-pressure pump override is \" + (enabled ? \"enabled in demo mode.\" : \"disabled in demo mode.\"));\n"
"        return;\n"
"      }\n"
"\n"
"      try {\n"
"        const response = await fetch(\"/admin/override\", {\n"
"          method: \"POST\",\n"
"          headers: { \"Content-Type\": \"application/json\" },\n"
"          body: JSON.stringify({ pump, enabled })\n"
"        });\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        setText(\"overrideNotice\", \"Low-pressure pump override is now \" + (enabled ? \"enabled.\" : \"disabled.\"));\n"
"        getSensorData();\n"
"      } catch (error) {\n"
"        setText(\"overrideNotice\", \"Firmware still needs the /admin/override route before it can apply pump overrides.\");\n"
"      }\n"
"    }\n"
"\n"
"    function updateAutonomousModeDisplay(enabled) {\n"
"      setChecked(\"autonomousModeSwitch\", enabled);\n"
"      const statusEl = document.getElementById(\"autonomousModeStatus\");\n"
"      if (statusEl) {\n"
"        statusEl.textContent = \"Autonomous Mode: \" + (enabled ? \"ON\" : \"OFF\");\n"
"        statusEl.className = enabled ? \"state-good\" : \"state-warn\";\n"
"      }\n"
"    }\n"
"\n"
"    async function setAutonomousMode(enabled) {\n"
"      const confirmationText = enabled\n"
"        ? \"Enable Autonomous Mode? This sets LP Enable, HP Enable, Float Switch Check, and Voltage Protection Check to ON and clears the LP override. Those settings stay independently editable afterward.\"\n"
"        : \"Disable Autonomous Mode? This only turns off the Autonomous Mode indicator \\u2014 LP Enable, HP Enable, and the safety checks stay as they currently are.\";\n"
"\n"
"      if (!window.confirm(confirmationText)) {\n"
"        setChecked(\"autonomousModeSwitch\", !enabled);\n"
"        return;\n"
"      }\n"
"\n"
"      if (demoMode) {\n"
"        lastData.autonomousMode = enabled;\n"
"        if (enabled) {\n"
"          lastData.pump1Enabled = true;\n"
"          lastData.pump2Enabled = true;\n"
"          lastData.conditionChecks = { float: true, lvd: true };\n"
"          lastData.lpOverride = false;\n"
"        }\n"
"        updatePage(lastData);\n"
"        setText(\"autonomousModeNotice\", \"Demo mode: Autonomous Mode \" + (enabled ? \"enabled.\" : \"disabled.\"));\n"
"        return;\n"
"      }\n"
"\n"
"      try {\n"
"        const response = await fetch(\"/admin/autonomous\", {\n"
"          method: \"POST\",\n"
"          headers: { \"Content-Type\": \"application/json\" },\n"
"          body: JSON.stringify({ enabled })\n"
"        });\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        setText(\"autonomousModeNotice\", \"Autonomous Mode is now \" + (enabled ? \"enabled.\" : \"disabled.\"));\n"
"        getSensorData();\n"
"      } catch (error) {\n"
"        setChecked(\"autonomousModeSwitch\", !enabled);\n"
"        setText(\"autonomousModeNotice\", \"Firmware still needs the /admin/autonomous route before this switch can control the real setting.\");\n"
"      }\n"
"    }\n"
"\n"
"    function syncVoltageInputs(which, fromNumber = false) {\n"
"      const slider = document.getElementById(which + \"Slider\");\n"
"      const number = document.getElementById(which + \"Input\");\n"
"      if (fromNumber) slider.value = number.value;\n"
"      else number.value = slider.value;\n"
"\n"
"      const lvd = Number(document.getElementById(\"lvdInput\").value);\n"
"      const mvr = Number(document.getElementById(\"mvrInput\").value);\n"
"      if (Number.isFinite(lvd) && Number.isFinite(mvr)) {\n"
"        setText(\"voltageRuleText\", \"The system will shut down at \" + lvd.toFixed(1) + \" V and may restart at \" + mvr.toFixed(1) + \" V.\");\n"
"      }\n"
"    }\n"
"\n"
"    async function saveProtectionSettings() {\n"
"      const lvd = Number(document.getElementById(\"lvdInput\").value);\n"
"      const mvr = Number(document.getElementById(\"mvrInput\").value);\n"
"\n"
"      if (!Number.isFinite(lvd) || !Number.isFinite(mvr)) {\n"
"        setText(\"adminNotice\", \"Enter valid voltage values first.\");\n"
"        return;\n"
"      }\n"
"\n"
"      if (mvr <= lvd) {\n"
"        setText(\"adminNotice\", \"Restart voltage must be higher than the shutdown voltage.\");\n"
"        return;\n"
"      }\n"
"\n"
"      if (demoMode) {\n"
"        lastData.lvd = lvd;\n"
"        lastData.mvr = mvr;\n"
"        updatePage(lastData);\n"
"        setText(\"adminNotice\", \"Demo mode: voltage protection values saved in this browser.\");\n"
"        return;\n"
"      }\n"
"\n"
"      try {\n"
"        const response = await fetch(\"/admin/settings\", {\n"
"          method: \"POST\",\n"
"          headers: { \"Content-Type\": \"application/json\" },\n"
"          body: JSON.stringify({ lvd, mvr })\n"
"        });\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        setText(\"adminNotice\", \"Voltage protection settings applied to F.R.O.G.S.\");\n"
"        getSensorData();\n"
"      } catch (error) {\n"
"        setText(\"adminNotice\", \"Firmware still needs the /admin/settings route before voltage settings can be saved.\");\n"
"      }\n"
"    }\n"
"\n"
"\n"
"    async function resetDefaults() {\n"
"      const confirmed = window.confirm(\"Reset Admin settings to firmware defaults? This should restore LVD, MVR, condition checks, pump enable settings, and LP override to their default values.\");\n"
"      if (!confirmed) return;\n"
"\n"
"      if (demoMode) {\n"
"        lastData.lvd = demoData.lvd;\n"
"        lastData.mvr = demoData.mvr;\n"
"        lastData.conditionChecks = { ...demoData.conditionChecks };\n"
"        lastData.lpOverride = false;\n"
"        lastData.pump1Enabled = true;\n"
"        lastData.pump2Enabled = true;\n"
"        updateAdminModeDisplay(false);\n"
"        updatePage(lastData);\n"
"        setText(\"resetNotice\", \"Demo mode: Admin defaults restored.\");\n"
"        return;\n"
"      }\n"
"\n"
"      try {\n"
"        const response = await fetch(\"/admin/reset\", {\n"
"          method: \"POST\",\n"
"          headers: { \"Content-Type\": \"application/json\" },\n"
"          body: JSON.stringify({ reset: true })\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error(\"ESP32 returned HTTP \" + response.status);\n"
"        setText(\"resetNotice\", \"Admin defaults restored.\");\n"
"        getSensorData();\n"
"        getAdminMode();\n"
"      } catch (error) {\n"
"        setText(\"resetNotice\", \"Firmware still needs the /admin/reset route before the webpage can reset the real default values.\");\n"
"      }\n"
"    }\n"
"\n"
"    document.querySelectorAll(\".tab-btn\").forEach(button => {\n"
"      button.addEventListener(\"click\", () => {\n"
"        document.querySelectorAll(\".page\").forEach(page => page.classList.remove(\"active\"));\n"
"        document.querySelectorAll(\".tab-btn\").forEach(tab => tab.classList.remove(\"active\"));\n"
"        document.getElementById(button.dataset.page).classList.add(\"active\");\n"
"        button.classList.add(\"active\");\n"
"        window.scrollTo({ top: 0, behavior: \"smooth\" });\n"
"      });\n"
"    });\n"
"\n"
"    setInterval(getSensorData, 3000);\n"
"    getSensorData();\n"
"  </script>\n"
"</body>\n"
"</html>\n";
